---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Apt install required system packages.
  apt: pkg={{item}} state=installed
  with_items: apt_system_packages
  
- name: Check installed pip version
  shell: pip -V
  register: common_pip_version
  changed_when: False
  ignore_errors: True
  always_run: True

- name: Force easy_install of pip
  shell: easy_install -U pip
  when: "'6.0.8' not in common_pip_version.stdout"
