---
- name: Download docker-machine
  get_url: url={{docker_machine_url}} dest='/usr/local/bin/docker-machine' mode=0755

- name: Install Docker With Docker Machine
  command: 'docker-machine create --driver "generic" --generic-ip-address {{ docker_machine_installation_ip }} --generic-ssh-user "ubuntu" --generic-ssh-key "/etc/ssh/ssh_host_rsa_key" --generic-ssh-port "22" {{ docker_machine_installation_ip | regex_replace("\\\\.", "-") }}'
